let pc,dc,role;const $=x=>document.getElementById(x);const cfg={iceServers:[{urls:"stun:stun.l.google.com:19302"}]};
function make(){pc=new RTCPeerConnection(cfg);pc.onconnectionstatechange=()=>{if(pc.connectionState==="connected"){$("setup").classList.add("hidden");$("chat").classList.remove("hidden");$("status").textContent="متصل ✓"}else $("status").textContent=pc.connectionState};pc.ondatachannel=e=>channel(e.channel);pc.onicecandidate=e=>{if(!e.candidate) $("local").value=enc(pc.localDescription)}}
function channel(x){dc=x;dc.onopen=()=>{$("setup").classList.add("hidden");$("chat").classList.remove("hidden")};dc.onmessage=e=>{let m=JSON.parse(e.data);if(m.type==="msg"){add(m,false);dc.send(JSON.stringify({type:"seen",id:m.id}))}else if(m.type==="seen")seen(m.id)}}
function enc(x){return btoa(unescape(encodeURIComponent(JSON.stringify(x))))}function dec(x){return JSON.parse(decodeURIComponent(escape(atob(x.trim()))))}
async function gather(){if(pc.iceGatheringState==="complete")return;await new Promise(r=>{let f=()=>{if(pc.iceGatheringState==="complete"){pc.removeEventListener("icegatheringstatechange",f);r()}};pc.addEventListener("icegatheringstatechange",f);setTimeout(r,12000)})}
$("offerBtn").onclick=async()=>{role="offer";make();channel(pc.createDataChannel("chat"));await pc.setLocalDescription(await pc.createOffer());$("status").textContent="أرسل الكود للهاتف 2";await gather();$("local").value=enc(pc.localDescription)}
$("answerBtn").onclick=()=>{role="answer";make();$("status").textContent="الصق كود الهاتف 1"}
$("connect").onclick=async()=>{try{await pc.setRemoteDescription(dec($("remote").value));if(role==="answer"){await pc.setLocalDescription(await pc.createAnswer());await gather();$("local").value=enc(pc.localDescription);$("status").textContent="أرسل كود الرد للهاتف 1"}else $("status").textContent="جاري الاتصال..."}catch(e){$("status").textContent="الكود غير صالح"}}
$("copy").onclick=()=>navigator.clipboard.writeText($("local").value)
$("form").onsubmit=e=>{e.preventDefault();let t=$("input").value.trim();if(!t||!dc||dc.readyState!=="open")return;let m={type:"msg",id:crypto.randomUUID(),text:t};dc.send(JSON.stringify(m));add(m,true);$("input").value=""}
function add(m,mine){let d=document.createElement("div");d.className="bubble "+(mine?"mine":"");d.dataset.id=m.id;d.innerHTML="<div>"+esc(m.text)+"</div>"+(mine?'<span class="meta ticks">✓✓</span>':"");$("messages").appendChild(d);$("messages").scrollTop=$("messages").scrollHeight}
function seen(id){let x=document.querySelector('[data-id="'+id+'"] .ticks');if(x){x.textContent="✓✓";x.style.color="#1687d9"}}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("reset").onclick=()=>location.reload();